name: Build and Test WinSatUi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      run: nuget restore WinSatUi.sln

    - name: Build
      run: msbuild WinSatUi.sln /p:Configuration=Release

    - name: Run tests
      run: |
        # Add your test runner command here if you have tests
        echo "No tests to run"
